import Head from 'next/head'
import Layout from '../../components/layout'
import Filters from '../../components/search/filters'
import AccommodationDetails from '../../components/accommodations/details'

export default function Accommodation() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1 className="mb-6">
          Accommodation
        </h1>

        <div className="flex flex-col space-y-6">
            <Filters options={[{name: 'Ukraine'}]} />
            <AccommodationDetails />
        </div>
      </Layout>
    </div>
  )
}

