import Head from 'next/head'
import Layout from '../components/layout'
import Filters from '../components/search/filters'
import SearchResults from '../components/search/results'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1 className="mb-6">
          Listings
        </h1>

        <div className="flex flex-col space-y-6">
            <Filters options={[{name: 'Ukraine'}]} />
            <SearchResults />
        </div>
      </Layout>
    </div>
  )
}
